POST http://127.0.0.1:8000/api/register/ HTTP/1.1
content-type: application/json

{
    "username": "sample2",
    "password": "test1234"
}



###
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "sample",
    "password": "test1234"
}


###


POST http://127.0.0.1:8000/api/handleChat/ HTTP/1.1
content-type: application/json
Authorization: Token 8374699df8052648d396786f41dd7f2168860c58

{
    "user_to_message" : 3
}



